CREATE DATABASE EPID;
CREATE TABLE CITY_DT(`PROVINCESHORTNAME` VARCHAR(20),`CITYNAME` VARCHAR(20),`CONFIRMEDCOUNT` VARCHAR(10),`CUREDCOUNT` VARCHAR(10),`DEADCOUNT` VARCHAR(10),`DT` VARCHAR(10));
CREATE TABLE PROVINCE_DT(`PROVINCESHORTNAME` VARCHAR(20),`CONFIRMEDCOUNT` VARCHAR(10),`CUREDCOUNT` VARCHAR(10),`DEADCOUNT` VARCHAR(10),`DT` VARCHAR(10));
